--- #YAML:1.0
name:               Image-Pbm
version:            0.04
abstract:           Load, create, manipulate and save pbm image files.
author:
    - Steffen Goeldner
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Image::PBMlib:  2
    Image::Xbm:     1.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
